behaviors:
  RollerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 100
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1
      curiosity:
        strength: 0.5
        gamma: 0.99
        encoding_size: 256
        learning_rate: 3.0e-4

      gail:
        strength: 0.5
        gamma: 0.99
        encoding_size: 128
        demo_path: D:/Unity/Projects/CS-662/Assets/Assingnment/Assignment 4/Demonstration File/Question 1.demo
        learning_rate: 3.0e-4
        use_actions: false
        use_vail: false
    behavioral_cloning:
      strength: 0.5
      demo_path: D:/Unity/Projects/CS-662/Assets/Assingnment/Assignment 4/Demonstration File/Question 1.demo
      batch_size: 512
      num_epoch: 3
    max_steps: 60000
    time_horizon: 64
    summary_freq: 10000
